In [3]:
import pandas as pd

In [4]:
pokedex = pd.read_csv(r'../../data/csv/pokedex.csv')
pokedex

,Unnamed: 0.1,Unnamed: 0,pokedex_number,english_name,german_name,generation,species,type_1,type_2,type_number,...,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,japanese_name
0,0,0,1,Bulbasaur,Bisasam,1,Seed Pokémon,Grass,Poison,2,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,フシギダネ (Fushigidane)
1,1,1,2,Ivysaur,Bisaknosp,1,Seed Pokémon,Grass,Poison,2,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,フシギソウ (Fushigisou)
2,2,2,3,Venusaur,Bisaflor,1,Seed Pokémon,Grass,Poison,2,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,フシギバナ (Fushigibana)
3,3,3,4,Charmander,Glumanda,1,Lizard Pokémon,Fire,NaN,1,...,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5,ヒトカゲ (Hitokage)
4,4,4,5,Charmeleon,Glutexo,1,Flame Pokémon,Fire,NaN,1,...,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5,リザード (Lizardo)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
381,381,381,382,Kyogre,Kyogre,3,Sea Basin Pokémon,Water,NaN,1,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,カイオーガ (Kyogre)
382,382,382,383,Groudon,Groudon,3,Continent Pokémon,Ground,NaN,1,...,1.0,1.0,1.0,0.5,1.0,1.0,1.0,1.0,1.0,グラードン (Groudon)
383,383,383,384,Rayquaza,Rayquaza,3,Sky High Pokémon,Dragon,Flying,2,...,1.0,1.0,0.5,2.0,1.0,2.0,1.0,1.0,2.0,レックウザ (Rayquaza)
384,384,384,385,Jirachi,Jirachi,3,Wish Pokémon,Steel,Psychic,2,...,0.5,2.5,1.0,0.5,2.0,0.5,2.0,0.5,0.5,ジラーチ (Jirachi)
385,385,385,386,Deoxys Normal Forme,Deoxys,3,DNA Pokémon,Psychic,NaN,1,...,1.0,0.5,2.0,1.0,2.0,1.0,2.0,1.0,1.0,デオキシス (Deoxys)

In [13]:
pokedex.loc[ 24 ]

Unnamed: 0.1                     24
Unnamed: 0                       24
pokedex_number                   25
english_name                Pikachu
german_name                 Pikachu
generation                        1
species               Mouse Pokémon
type_1                     Electric
type_2                          NaN
type_number                       1
weight_kg                       0.6
height_m                        0.4
is_sub_legendary                  0
is_legendary                      0
is_mythical                       0
abilities_number                  2
ability_1                    Static
ability_2                       NaN
ability_hidden        Lightning Rod
total_points                    320
hp                               35
attack                           55
defense                          40
sp_attack                        50
sp_defense                       50
speed                            90
catch_rate                      190
base_friendship                  70
base_experience                 112
growth_rate             Medium Fast
egg_type_number                   2
egg_type_1                    Fairy
egg_type_2                    Field
percentage_male                 0.5
egg_cycles                       10
against_normal                  1.0
against_fire                    1.0
against_water                   1.0
against_electric                0.5
against_grass                   1.0
against_ice                     1.0
against_fight                   1.0
against_poison                  1.0
against_ground                  2.0
against_flying                  0.5
against_psychic                 1.0
against_bug                     1.0
against_rock                    1.0
against_ghost                   1.0
against_dragon                  1.0
against_dark                    1.0
against_steel                   0.5
against_fairy                   1.0
japanese_name       ピカチュウ (Pikachu)
Name: 24, dtype: object

In [ ]:
pokedex.loc[ 24 ]

In [5]:
pokedex[pokedex['german_name'] == 'Pikachu']

,Unnamed: 0.1,Unnamed: 0,pokedex_number,english_name,german_name,generation,species,type_1,type_2,type_number,...,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,japanese_name
24,24,24,25,Pikachu,Pikachu,1,Mouse Pokémon,Electric,NaN,1,...,0.5,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,ピカチュウ (Pikachu)